---

apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: proxy
  name: proxy

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: proxy
  name: proxy
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - update
      - patch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: proxy
  name: proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxy
subjects:
  - kind: ServiceAccount
    name: proxy
